//go:build e2e

package e2e_generated

import (
	"context"
	"os/exec"
	"time"

	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"
)

// Auto-generated by docsyncer from: ../sail-operator/docs/general/istiod-ha.adoc
// Source type: asciidoc
// DO NOT EDIT — this file is regenerated on every run.

var _ = Describe("Istiod HA Autoscaling", func() {

	It("Create namespace and apply Istio HA autoscaling", func() {
		{
			By("Create namespace and apply Istio HA autoscaling")
			dur, err := time.ParseDuration("30s")
			Expect(err).ToNot(HaveOccurred())
			ctx, cancel := context.WithTimeout(context.Background(), dur)
			defer cancel()
			cmd := exec.CommandContext(ctx, "/bin/sh", "-c", "kubectl create ns istio-system\ncat <<EOF | kubectl apply -f-\napiVersion: sailoperator.io/v1\nkind: Istio\nmetadata:\n  name: default\nspec:\n  namespace: istio-system\n  values:\n    pilot:\n      autoscaleMin: 2\n      autoscaleMax: 5\n      cpu:\n        targetAverageUtilization: 80\n      memory:\n        targetAverageUtilization: 80\nEOF")
			output, err := cmd.CombinedOutput()
			Expect(err).ToNot(HaveOccurred(), string(output))
		}
	})

	It("Verify istiod HA pods (autoscaling)", func() {
		{
			By("Verify istiod HA pods (autoscaling)")
			dur, err := time.ParseDuration("30s")
			Expect(err).ToNot(HaveOccurred())
			ctx, cancel := context.WithTimeout(context.Background(), dur)
			defer cancel()
			{
				var lastOutput []byte
				var lastErr error
				for attempt := 1; attempt <= 4; attempt++ {
					cmd := exec.CommandContext(ctx, "kubectl", "get", "pods", "-n", "istio-system", "-l", "app=istiod")
					lastOutput, lastErr = cmd.CombinedOutput()
					if lastErr == nil {
						break
					}
					if attempt <= 3 {
						time.Sleep(5 * time.Second)
					}
				}
				Expect(lastErr).ToNot(HaveOccurred(), string(lastOutput))
			}
		}
	})
})
